export const TokenType = {
  Keyword: 'Keyword',
  WhiteSpace: 'WhiteSpace',
  SequenceNumberLiteral: 'SequenceNumberLiteral',
  Comment: 'Comment',
  NumericLiteral: 'NumericLiteral',
  Operator: 'Operator',
  EXEC: 'EXEC',
  IdentificationArea: 'IdentificationArea',
  Identifier: 'Identifier',
  EOF: 'EOF',
  StringLiteral: 'StringLiteral',
  Terminator: 'Terminator',
  NotIdentified: 'NotIdentified',
};
